name: QA and Release

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js with required version for OIDC
        uses: actions/setup-node@v4
        with:
          # Trusted publishing requires npm CLI version 11.5.1 or later and Node version 22.14.0 or higher
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org'

      - name: install required npm version for OIDC
        # Trusted publishing requires npm CLI version 11.5.1 or later and Node version 22.14.0 or higher
        run: npm install -g npm@11.5.1

      - name: Install dependencies
        run: npm install

      - name: QA
        run: npm run qa

      - name: Build project
        run: npm run build

      - name: determine next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.7.1
        with:
          prefix: 'v'

      - name: fail if no next release version
        if: ${{ steps.get_next_version.outputs.hasNextVersion != 'true' }}
        run: |
          echo "There is no next release version. hasNextVersion is false"
          exit 1

      - name: Check if version-release is set up correctly
        uses: johanna-herrmann/node-check-version@v1
        with:
          next_version: ${{ steps.get_next_version.outputs.version }}

      - name: Publish
        #provenance flag sometimes required, due to a bug?
        #https://philna.sh/blog/2026/01/28/trusted-publishing-npm/
        run: npm publish --provenance

      - name: Tag release commit
        run: |
          NEXT_VERSION=${{ steps.get_next_version.outputs.version }}
          git tag $NEXT_VERSION
          git push origin $NEXT_VERSION
